import { NextRequest, NextResponse } from 'next/server';

interface RfpVendorInput {
  name: string;
  category: string;
  reasonSummary?: string;
}

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null);
  if (!body || typeof body.problem !== 'string' || !Array.isArray(body.vendors)) {
    return NextResponse.json({ error: 'Invalid request brief payload.' }, { status: 400 });
  }

  const vendors: RfpVendorInput[] = body.vendors;
  const today = new Date().toISOString().slice(0, 10);

  const sections = [
    `# Requirements Brief (Draft)`,
    ``,
    `Generated by Galymer on ${today}. This is a first-draft starting point for your internal RFP or requirements catalogue -- review and edit before sending to vendors.`,
    ``,
    `## 1. Business Problem`,
    body.problem,
    ``,
    `## 2. Evaluation Context`,
    `- Company size: ${body.companySize ?? 'not specified'}`,
    `- Implementation complexity tolerance: ${body.complexityTolerance ?? 'not specified'}`,
    `- Existing technology stack: ${(body.existingStack ?? []).join(', ') || 'none specified'}`,
    ``,
    `## 3. Shortlisted Partners`,
    ...vendors.flatMap((v, i) => [
      `### ${i + 1}. ${v.name} (${v.category})`,
      v.reasonSummary ? `Why shortlisted: ${v.reasonSummary}` : '',
      `- [ ] Confirm licensing model and total cost of ownership`,
      `- [ ] Confirm implementation timeline and required internal resources`,
      `- [ ] Confirm data residency / compliance requirements`,
      `- [ ] Request 2 reference customers of comparable size and industry`,
      ``,
    ]),
    `## 4. Open Questions For Vendors`,
    `- What does a typical implementation timeline look like for a company of our size?`,
    `- Which of our existing systems have pre-built connectors vs. custom integration work?`,
    `- What does year-2 total cost of ownership look like after initial implementation?`,
    ``,
    `---`,
    `Draft generated automatically. Verify all vendor-specific claims before distribution.`,
  ];

  return NextResponse.json({ markdown: sections.join('\n') });
}
